logging:
  level:
    org.dclou.example.demogpb.order.clients: DEBUG
    org.springframework.security: DEBUG

server:
  port: 9991
  session:
    cookie:
      name: JSESSIONIDAUTHSRV

security:
  user:
    password: password
