sudo: required

services:
  - docker

addons:
  ssh_known_hosts: 178.159.32.129

script:
  - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B package

before_deploy:
  - openssl aes-256-cbc -K $encrypted_20b9ef8ac179_key -iv $encrypted_20b9ef8ac179_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - gpg --fast-import travissign.asc
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy/deploy_rsa
  - ssh-add deploy/deploy_rsa
  
deploy:
  provider: script
  skip_cleanup: true
  script: deploy/deploy.sh 178.159.32.129
  on:
    branch: release
