sudo: required
language: java
services:
  - docker

install:
  - docker pull java:8

script:
  - mvn test -B test

deploy:
  skip_cleanup: true
  provider: script
  script: |
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    mvn -B package -Pdocker_deploy
