# Docker Schema ref: https://github.com/aanand/compose-file/blob/master/schema/data/config_schema_v3.0.json
# Difference: https://docs.docker.com/compose/compose-file/compose-versioning/#version-21
# How-to swarm cluster: https://codefresh.io/blog/deploy-docker-compose-v3-swarm-mode-cluster/

version: '3'
services:
  admin-service:
    image: dclou/platform-admin-service:latest
    environment:
      JAVA_MEM: "-Xms250m -Xmx512m -XX:CompressedClassSpaceSize=300m -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:-TieredCompilation -Xss256k -XX:+UseG1GC -XX:+UseStringDeduplication"
      JAVA_EXT: "-Djava.security.egd=file:/dev/./urandom"
    ports:
      - "7070:7070"

  zipkin-service:
    image: dclou/platform-zipkin-service:latest
    environment:
      JAVA_MEM: "-Xms250m -Xmx512m -XX:CompressedClassSpaceSize=300m -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:-TieredCompilation -Xss256k -XX:+UseG1GC -XX:+UseStringDeduplication"
      JAVA_EXT: "-Djava.security.egd=file:/dev/./urandom"
    ports:
      - "9411:9411"

  auth-service:
    image: dclou/platform-auth-service:latest
    environment:
      JAVA_MEM: "-Xms250m -Xmx512m -XX:CompressedClassSpaceSize=300m -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:-TieredCompilation -Xss256k -XX:+UseG1GC -XX:+UseStringDeduplication"
      JAVA_EXT: "-Djava.security.egd=file:/dev/./urandom"
    ports:
      - "9991:9991"

  gateway-service:
    image: dclou/platform-gateway-service:latest
    environment:
      JAVA_MEM: "-Xms250m -Xmx512m -XX:CompressedClassSpaceSize=300m -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:-TieredCompilation -Xss256k -XX:+UseG1GC -XX:+UseStringDeduplication"
      JAVA_EXT: "-Djava.security.egd=file:/dev/./urandom"
    ports:
      - "8080:8080"

  turbine-service:
    image: dclou/platform-turbine-service:latest
    environment:
      JAVA_MEM: "-Xms250m -Xmx512m -XX:CompressedClassSpaceSize=300m -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:-TieredCompilation -Xss256k -XX:+UseG1GC -XX:+UseStringDeduplication"
      JAVA_EXT: "-Djava.security.egd=file:/dev/./urandom"
    ports:
      - "8485:8485"
