# Docker Schema ref: https://github.com/aanand/compose-file/blob/master/schema/data/config_schema_v3.0.json
# Difference: https://docs.docker.com/compose/compose-file/compose-versioning/#version-21
# How-to swarm cluster: https://codefresh.io/blog/deploy-docker-compose-v3-swarm-mode-cluster/

version: '3'
services:

  zipkin-service:
    image: dclou/platform-zipkin-service

  admin-service:
    image: dclou/platform-admin-service
    ports:
      - "7070:7070"

  auth-service:
    image: dclou/platform-auth-service

  config-service:
    image: dclou/platform-config-service

  sleuth-service:
    image: dclou/platform-sleuth-service

  gateway-service:
    image: dclou/platform-gateway-service
    ports:
      - "8080:8080"
