# Docker Schema ref: https://github.com/aanand/compose-file/blob/master/schema/data/config_schema_v3.0.json
# Difference: https://docs.docker.com/compose/compose-file/compose-versioning/#version-21
# How-to swarm cluster: https://codefresh.io/blog/deploy-docker-compose-v3-swarm-mode-cluster/

version: '3'
volumes:
  data-prometheus:
  data-logging:
  data-elasticsearch:

services:

  discovery-service:
    image: dclou/platform-discovery-service:latest
    depends_on: # https://docs.docker.com/compose/startup-order/
      - rabbit-mon
    ports:
      - "8761:8761"

  config-service:
    image: dclou/platform-config-service:latest
    ports:
      - "8888:8888"

  portainer:
    image: portainer/portainer
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - "9000:9000"

  prometheus:
    image: dclou/platform-prometheus:latest
    volumes:
      - data-prometheus:/prometheus

  fluentd:
    image: dclou/platform-fluentd:latest
    volumes:
      - data-logging:/fluentd/log

  elasticsearch:
    image: elasticsearch
    volumes:
      - data-elasticsearch:/usr/share/elasticsearch/data
