#Common DEFAULT settings
spring:
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

  sleuth:
    sampler:
      percentage: 1

encrypt:
  failOnError: false
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
          enabled: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
      hostname: ${spring.application.name}
      prefer-ip-address: false
      lease-expiration-duration-in-seconds: 60
      lease-renewal-interval-in-seconds: 30

      statusPageUrl: http://${eureka.instance.hostname}:${management.port}/${management.context-path}/info
      secureHealthCheckUrl: http://${eureka.instance.hostname}:${management.port}/${management.context-path}/health
      homePageUrl: http://${eureka.instance.hostname}:${server.port}/
      securePort: ${server.port}
      securePortEnabled: false
      nonSecurePortEnabled: true
      metadataMap:
        management.context-path: ${management.context-path}
        management.port: ${management.port}
        instanceId: ${spring.application.name}:${random.value}

management:
  port: ${server.port}
  security.enabled: false
  context-path: /mgmt

# Turn off the basic endpoint security (helps with [Registry]
security:
  basic:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 5000

