# DOCS http://codecentric.github.io/spring-boot-admin/1.5.0/#_hystrix_ui_module

server:
  port: ${PORT:7070}

info:
  version: 1.5.0
  owner: \u674E\u9F99

#management.context-path: /mgmt
#endpoints.health.path: /health

spring:
  boot:
    admin:
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream

#      turbine:
#        clusters: default
#        url: http://localhost:8989/turbine.stream
#        client.prefer-ip: true